session_name: default
start_directory: ~/
windows:
  - window_name: main
    layout: main-vertical
    panes:
      - focus: true
      - shell_command:
          - claude
    options:
      main-pane-width: 75%

