run-shell "powerline-daemon -q || true"          
set -g status on
set -g status-interval 2                       
set -g status-left-length 60                   
set -g status-right-length 120                 
set -g status-left "#(powerline tmux left)"    
set -g status-right "#(powerline tmux right)"  
